version: '2'

services:
#   visits-service:
#    image: springcommunity/spring-petclinic-visits-service
#    container_name: visits-service
#    mem_limit: 512M
#    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "org.springframework.boot.loader.JarLauncher"]
#    ports:
#     - 8082:8082
#     
#   visits-service2:
#    image: springcommunity/spring-petclinic-visits-service
#    container_name: visits-service2
#    mem_limit: 512M
#    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "org.springframework.boot.loader.JarLauncher"]
#    ports:
#     - 8092:8092
#
#   vets-service:
#    image: springcommunity/spring-petclinic-vets-service
#    container_name: vets-service
#    mem_limit: 512M
#    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "org.springframework.boot.loader.JarLauncher"]
#    ports:
#     - 8083:8083

  api-gateway:
    image: springcommunity/spring-petclinic-api-gateway
    container_name: api-gateway
    mem_limit: 512M
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "org.springframework.boot.loader.JarLauncher"]
    ports:
     - 8080:8080